{% set name = "SAS_kernel" %}
{% set version = "2.2.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "3ebddf4a85311b718acf12f56cc342f808039e83771cf0ae2b1f2f163c98c6b8" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] | lower }}/{{ name | lower }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1000
  script: NO_KERNEL_INSTALL=1 python setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [not linux]
  skip: true  # [py2k]

requirements:
  build:
    - python 
    - setuptools
    - ipython >=4
  run:
    - python
    - ipython >=4
    - saspy >=1.2.2
    - pygments
    - metakernel >=0.18.0
    - jupyter_client >=4.4.0

test:
  imports:
    - sas_kernel

about:
  home: https://github.com/sassoftware/sas_kernel
  license: Apache 2.0
  summary: A Jupyter kernel for SAS

extra:
  recipe-maintainers:
    - danielfrg
