{% set name = "SAS_kernel" %}
{% set version = "2.4.10" %}
{% set hash_type = "sha256" %}
{% set hash_val = "81561d12a35bfac9cec9b30f41373ce863f3f29eee4ca21da7ee0f82dbdbac7f" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] | lower }}/{{ name | lower }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: NO_KERNEL_INSTALL=1 python setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [not linux]
  skip: true  # [py2k]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - ipython >=7.*
    - jupyter_client >=6.*
    - metakernel >=0.27.5

  run:
    - python
    - ipython >=7.*
    - metakernel >=0.27.5
    - jupyter_client >=6.*
    - saspy >=3.6
    

test:
  imports:
    - sas_kernel
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sassoftware/sas_kernel
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A Jupyter kernel for SAS
  description: |
      A Jupyter kernel for SAS. This opens up all the data manipulation and
      analytics capabilities of your SAS system within a notebook interface.
      Use the Jupyter Notebook interface to execute SAS code and view results
      inline.
  dev_url: https://github.com/sassoftware/sas_kernel
  doc_url: https://sassoftware.github.io/sas_kernel

extra:
  recipe-maintainers:
    - danielfrg
