{% set name = "SAS_kernel" %}
{% set version = "2.4.6" %}
{% set hash_type = "sha256" %}
{% set hash_val = "54fdf913442872a8a2b13b3ae5e104d5bc9171725487904e5a151587ca9b7dd5" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] | lower }}/{{ name | lower }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: NO_KERNEL_INSTALL=1 python setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [not linux]
  skip: true  # [py2k]

requirements:
  host:
    - python
    - setuptools
    - ipython >=7.*
    - jupyter_client >=6.*
  run:
    - python
    - ipython >=7.*
    - saspy >=3.6
    - pygments
    - metakernel >=0.27.5
    - jupyter_client >=6.*
    

test:
  imports:
    - sas_kernel

about:
  home: https://github.com/sassoftware/sas_kernel
  license: Apache 2.0
  license_family: Apache
  summary: A Jupyter kernel for SAS
  description: |
      A Jupyter kernel for SAS. This opens up all the data manipulation and
      analytics capabilities of your SAS system within a notebook interface.
      Use the Jupyter Notebook interface to execute SAS code and view results
      inline.
  dev_url: https://github.com/sassoftware/sas_kernel
  doc_url: https://sassoftware.github.io/sas_kernel

extra:
  recipe-maintainers:
    - danielfrg
