travis:
  secure:
    BINSTAR_TOKEN: GEWDoQ7/x5W/5hcayktEI48uOeuK9eBUvVcMMVah/TpImQEsvhcolqQ/JrItGpx8YfUtRfbBl/QB92mGLp9V72Xig+Dt5+YNP0aP+N5IoglwihAlXFdwWIVV9YO5JbxG97qtCeI7y3W2FR+ZE3qkFPeqyD0/BHF76nBFqI4n5FEPtBHtIKupQWNd/p5WgbnwGJnWNj3n9hRwy4NN+ZMNUhF9b/3GNPhK4X4EknN9/+/WxCNDnm7YlzV5b+iwJAzP6/evlIPQwf5PsSUVMzfhLaZhm++m6V41TNzHQ5wentlKNT0+ki+uej3NtHpmJGqkbJbUUzPDdDByqHNL5n3NaXRNbtivMQlgZWX4+nrewWD/g5es4iANtOq4N7Oq54aEPUzGibIfYSaJrE9GHkPXFoIOCLC6+V/h9gTTHR4vN1sGHhJOjPHkia2vm3k+708UGv0f11FR9UVwxOpUZmszeNcXXv+hA8QRhwvqysHy0T4xrwECGDgxS2P4OXLpTc2T5GhZvUX3yoiJGDvoU5SwZh8AahbQdsAtZmk9NqRTMSVjvKGGNX2Qe5MbpDTWBCiynkLczO7xxubk/NAHOkaenleBII0NJeBUu9xJR0z5vZ7QyiHZich7rICWsh8w8uuRWaMOKQAItsIBGR8wm2SgT2IUQAmWY83br1j/53hSka4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
